### PR TITLE
Support pre and post deploy actions for clouds and add NSX cloud post deploy

### PR DESCRIPTION
**Pull request by miguelaferreira**
`./kvm_local_deploy.py -c nsx_cluster` will now create a NSX cluster with 1 manger, 1 controller, 1 service node and 1 kvm host.

screen shot 2015-10-27 at 12 27 35

Next step is to have a config that adds a new controller to the cluster

### CODE REVIEW

**Comment by remibergsma** [comment]
FYI: I'm testing this now

**Comment by miguelaferreira** [comment]
ping @remibergsma PR should be better now. Can you please test?

I have a new one coming, and it would be great to get this done first.

**Comment by miguelaferreira** [comment]
ping @remibergsma @neubauerf @wilderrodrigues can someone review and merge this please?

**Comment by remibergsma** [comment]
@miguelaferreira Running the test now

**Comment by wilderrodrigues** [comment]
@miguelaferreira 

In order to test it, do I just need to run this ==> ./kvm_local_deploy.py -c nsx_cluster ?

Just asked because @remibergsma mentioned he is running a tes.

Cheers,
Wilder

**Comment by miguelaferreira** [comment]
@wilderrodrigues run the command you mention, and check that you actually have a cluster.
- For that you need to access `https://nsxmgr1.cloud.lan` and add a controller to the manager (you wrote down the UI steps in a confluence page, so I assume you can figure it out).
- Then after adding a cluster you should check the transport zone and nodes.
- There should be a service node and a kvm node.

**Comment by wilderrodrigues** [comment]
@miguelaferreira 

Testing now.

**Comment by miguelaferreira** [comment]
Thanks @wilderrodrigues be sure to stop chef-client on your box, otherwise it can come by and screw the /data/shared dir and scripts disappear!

`sudo service chef-client stop`

**Comment by wilderrodrigues** [comment]
I thought of that, @miguelaferreira ... but didn't do! I like to live a dangerous life! ;)

**Comment by wilderrodrigues** [comment]
Works like a charm! Will merge it now!

image

**Comment by miguelaferreira** [comment]
cool!

**Comment by miguelaferreira** [comment]
now the next one :mask:

**Pull request merged**
