### PR TITLE
Add mysql-connector-python yum package.

### PR DESCRIPTION
**Pull request by borisroman**
It's needed to install marvin!

### CODE REVIEW

**Comment by remibergsma** [comment]
How come we never run into this before? Where did you see this going wrong?

Let's have a look together in a while :-)

**Comment by borisroman** [comment]
Looking into removing the Python-mysql package now!

**Comment by borisroman** [comment]
```
Preparing to package Apache CloudStack 4.7.1-SNAPSHOT
. preparing source tarball
. executing rpmbuild
error: Failed build dependencies:
        MySQL-python is needed by cloudstack-4.7.1-SNAPSHOT.el7.centos.x86_64
RPM Build Failed
```

It's being depended on by the yum packaging.

**Comment by DaanHoogland** [comment]
:+1: I ran into problems installing it with pip leading to errors during the zone deployment with Marvin.

**Comment by borisroman** [comment]
```
Processing ./tools/marvin/dist/Marvin-4.7.1-SNAPSHOT.tar.gz
Collecting mysql-connector-python>=1.1.6 (from Marvin===4.7.1-SNAPSHOT)
  Could not find a version that satisfies the requirement mysql-connector-python>=1.1.6 (from Marvin===4.7.1-SNAPSHOT) (from versions: )
No matching distribution found for mysql-connector-python>=1.1.6 (from Marvin===4.7.1-SNAPSHOT)
```

This is what happens when you don't have it installed!

**Comment by borisroman** [comment]
It was previously being installed via pip, but pip stopped providing the package.

**Pull request merged**
